### PR TITLE
remove all serial logging

### PR DESCRIPTION
**Pull request by sumnerboy12**

### CODE REVIEW

**Comment by sumnerboy12** [comment]
I have merged all the other PRs relating to this change to serial logging - but wanted to leave the LCD lib for you to review properly.

**Review by moinmoin-sh — COMMENTED** [review]
I built a new version with all changes and came to the conclusion that I would like to keep the serial logging for the LCD lib.

Reason:
- if something goes wrong with the logo we have no feedback from the FW for what reason. This becomes important as soon as maker add their own logo and many things can go wrong here.
- the LCD lib is fairly large. A logo requires ~5k, and we have two already (OXRS + maker). Usage of the LCD will require a somewhat powerfull MCU and in that case the ~250 byte for the serial logging doesn't matter.
- the Serial class is linked anyway so the savings are just the printed text

As a general comment, it looks unusual to me without the serial output. What I'm missing is a feedback when a conf is published. I could imagine that we'll miss the serial logging when it comes to debugging the UI. May be it would have been better to wrap the serial logging with #ifdef/#endif to have the ability to enable/disable serial logging at compile time (like generating debug / release versions)

**Comment by sumnerboy12** [comment]
Yeah I agree it is/will be handy at times - but no other Arduino libraries have this sort of verbose logging. The parent firmware sketch can have as much logging as it likes, so perhaps we should improve the library APIs to return error codes so the owning code can decide what to do about it, similar to what `PubSubClient` does with connection status?

That way you can return an `int` from `lcd.begin()` which indicates if there was a problem and what that problem was (as long as those codes are well documented).

**Comment by moinmoin-sh** [comment]
Yes, that is the common way to do it for errors. I was more thinking of  informational outputs. The downside would be that the firmware sketch would need to know what errors could be raised. 
If you feel better, we can remove the serial logging here for now (as you did for the other libs) to have it consistant.

**Pull request merged**
